import Image from 'next/image'
import Link from 'next/link'

import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <header className='flex items-center p-4 border-b-[1px] h-20'>
      <label className='first:w-20'>
        
      </label>
      <nav>
        <ul className='flex gap-4'>
          <li className='text-gray-700 font-medium'>
            <Link href="/">Colaboradores</Link>
          </li>
          <li className='text-gray-700 font-medium'>
            <Link href="/coffeeday">Café da manhã</Link>
          </li>
          <li className='text-gray-700 font-medium'>
            <Link href="/Itens">Itens</Link>
          </li>
        </ul>
      </nav>
      </header>
      <main className='p-4'>
        {children}
      </main>
      </body>
    </html>
  )
}
